spring.application.name=backend
spring.mongodb.uri=mongodb://businessgaming32_db_user:SHutAphPwHz02m52@ac-cmhxnqh-shard-00-00.tvhezjc.mongodb.net:27017,ac-cmhxnqh-shard-00-01.tvhezjc.mongodb.net:27017,ac-cmhxnqh-shard-00-02.tvhezjc.mongodb.net:27017/patient_system?ssl=true&replicaSet=atlas-oh96g9-shard-0&authSource=admin&appName=Cluster0
spring.data.mongodb.uri=mongodb://businessgaming32_db_user:SHutAphPwHz02m52@ac-cmhxnqh-shard-00-00.tvhezjc.mongodb.net:27017,ac-cmhxnqh-shard-00-01.tvhezjc.mongodb.net:27017,ac-cmhxnqh-shard-00-02.tvhezjc.mongodb.net:27017/patient_system?ssl=true&replicaSet=atlas-oh96g9-shard-0&authSource=admin&appName=Cluster0
server.address=0.0.0.0
server.port=8080
jwt.secret=361b2e4eb2475bf4e2a9369c61689890
jwt.expiration=86400000
